localhost

[all:vars]
ethereum_network_name=chetany

[node]
node-001 ansible_host=142.93.130.177 cloud=digitalocean cloud_region=ams3 
node-002 ansible_host=161.35.127.238 cloud=digitalocean cloud_region=nyc1 
node-003 ansible_host=178.128.115.177 cloud=digitalocean cloud_region=sgp1 

